on:
  # Trigger the workflow on merges to main or releases.
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # These are only needed because we don't have cosign published yet!
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: cosign
        run: go install  github.com/sigstore/cosign/cmd/cosign@eb0200a289e43359fde58c1a88409767a51cd8ad
      - name: login
        run: docker login --username dlorenc --password ${{ secrets.DockerLogin }}
      - name: build
        run: docker build . -t dlorenc/signed-container:$GITHUB_SHA
      - name: push
        run: docker push dlorenc/signed-container:$GITHUB_SHA
      - name: sign
        run: echo -n "${{secrets.CosignPassword}}" | cosign sign -key cosign.key -a git_sha=$GITHUB_SHA dlorenc/signed-container:$GITHUB_SHA
