on:
  # Trigger the workflow on merges to main or releases.
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # These are only needed because we don't have cosign published yet!
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: sigstore/cosign-installer@main
      - name: login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build
        run: docker build . -t ghcr.io/dlorenc/signed-container:$GITHUB_SHA
      - name: push
        run: docker push ghcr.io/dlorenc/signed-container:$GITHUB_SHA
      - name: sign
        run: echo -n "${{secrets.CosignPassword}}" | cosign sign -key cosign.key -a git_sha=$GITHUB_SHA ghcr.io/dlorenc/signed-container:$GITHUB_SHA
