on:
  release:
    types: 
      - created
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # These are only needed because we don't have cosign published yet!
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: sigstore/cosign-installer@main
      # Setup whatever creds you need to push to your registry.
      - name: login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # This flow assumes the images are built in CI first. We don't build a new one as part of the release.
      # We retag it.
      - name: pull-tag
        run: docker pull ghcr.io/dlorenc/signed-container:$GITHUB_SHA && docker tag ghcr.io/dlorenc/signed-container:$GITHUB_SHA ghcr.io/dlorenc/signed-container:$(git tag)
      - name: push
        run: docker push ghcr.io/dlorenc/signed-container:$(git tag)
      # And now we sign! We include the commit the image was built at and the git tag **in the signed portion**
      - name: sign
        run: echo -n "${{secrets.CosignPassword}}" | cosign sign -key cosign.key -a git_sha=$GITHUB_SHA -a git_tag=$(git tag) ghcr.io/dlorenc/signed-container:$(git tag)
